
refclock SHM 0 refid GPS offset 0.05 delay 0.5

#refclock SHM 1 refid PPS precision 1e-9
refclock PPS /dev/pps0 refid PPS0 lock GPS prefer
refclock PPS /dev/pps1 refid PPS1 lock GPS prefer

refclock SHM 2 refid PTP precision 1e-9

makestep 1 10
maxupdateskew 5

local stratum 1
manual
allow 192.168.0.101

pidfile /tmp/chronyd.pid

driftfile /var/lib/chrony/chrony.drift

#logdir /var/log/chrony
#log statistics tracking refclocks
#log tracking
noclientlog
logchange 0.1

dumponexit
dumpdir /var/lib/chrony

cmdallow 127.0.0.1

# sched_priority 1
lock_all

