###Vehicle classifier, 
### Provide Integer value as per DE_BasicVehicleClass definition of J2735 v2016
vehicle_class = 10

###Channel access hack for some RSUs
wsa_channel_access_hack = 1

###Enable WSA Selector
enable_wsa_forwarder = 1

###Enable diagnostic lights on the board
diagnostics_enabled = 1

###Below are the configuration for the Security - Comment the below line to turn off Security
onboardsecurity_configuration = 

### Provide Integer value as per DE_BasicVehicleRole definition in J2735 
vehicle_role = 0

###Below configuration for the Security verification enable or disable (1 for enable, all other values to disable)
#rxmsg_security_option = 0

############################################################################
############ RECOMMENDED TO NOT MODIFY ANYTHING BELOW THIS LINE ############
############################################################################

###List of PSIDs supported w.r.t Customer Requirements###
# PSID for Service 1
#PVD Messages
psid_service_used = 84

# PSID for Service 2
psid_service_used = 1020407E 

# PSID for Service 3
psid_service_used = 26

# PSID for Service 4
psid_service_used = 204096

# PSID for Service 5
psid_service_used = 2113686

psid_service_used = 20

###Enable BSM congestion control
enable_congestion_control = 1

###VAD configuration file
#vehicle_vad_conf_file = vad_vehicle.conf
vehicle_vad_conf_file = /config/ModelDeploymentRemovable.conf 

###Below are for the PVD setup
#Probe data interval in msec
vehicle_pvd_interval = 1000
###Enable PVD on probe message service available
vehicle_pvd_on_probe_service = 1

###Use u-blox GNSS interface
#use_ublox_gnss = 1

###Below configurations are for the Radio Configurations 
radio_0_default_channel=183
#radio_1_default_channel=183
#radio_0_service_channel=180
radio_bsmuper_txchannel = 183
radio_eva_txchannel = 183
radio_srmuper_txchannel = 183

###Below configuration is for the setting the BSM Tx Pwr - TxPower to use for BSM UPERs, 0 uses device default
radio_bsmuper_txpower = 20
radio_srmuper_txpower = 29

###The location of application configuration files
#config_dir

###Communication Logs details
log_pcap = false

#Transmit only if New GPS Data is available
vehicle_tx_new_gps_only = 1

###Use J2945 minimum transmission requirements - set to 1 and device will not transmit any BSM when no GPS fix
vehicle_use_minimum_tx_info = 1 

#For getting last known heading value
vehicle_heading_persist_file = /opt/danlaw/bin/vehicle.heading

#For getting last known path history data
path_history_storage_location = /opt/danlaw/bin/pathhistorydata.txt

#For path history and Path Prediction logging
#path_history_log_directory = /v2x_logs
#path_prediction_log_directory = /v2x_logs

#For path history stored previous location distance
path_history_reset_distance = 20.0

### udp forwarding details 
udp_forward_address = 192.168.0.101
udp_forward_port = 30005
udp_rx_forward_port = 10002
############################################################################
#Active message forward port number; 0- Disable;
active_message_port = 1516
